### ISSUE TITLE
Automate dependency on fuel

### ISSUE THREAD

**Issue by drdrwhite** [kkrawiec/fuel#8]
Currently, to build SWIM I have to checkout the fuel project next to it. Could we remove this manual step in the build process by automating the dependency? 

A quick first step would be to add this specific info. to the README.

**Comment by iwob** [comment]
By automating the dependency do you mean doing checkout of FUEL automatically? Or perhaps some dependency on its github source code?

**Comment by drdrwhite** [comment]
I think avoiding having to manually checkout another project in the parent directory would make the build easier. 

This could be achieved by deploying FUEL as a jar via Bintray, or by incorporating git into sbt via one of several methods, e.g. http://queirozf.com/entries/add-a-github-project-as-a-dependency-in-sbt

**Comment by iwob** [comment]
I pushed fix for this to SWIM. Thank you for the suggestion. Previous behaviour can be enabled by uncommenting appropriate line in build.sbt.

**Comment by kkrawiec** [comment]
@iwob : Thanks!

**Comment by drdrwhite** [comment]
Fantastic. Thank you. I realised I opened this issue in the wrong place, should have been in SWIM. Sorry about that.
